import * as ElementTag from '../ElementTags/ElementTags.ts'
import * as VirtualDomElements from '../VirtualDomElements/VirtualDomElements.ts'

const elementTagMap: Record<number, string> = {
  [VirtualDomElements.A]: ElementTag.A,
  [VirtualDomElements.Article]: ElementTag.Article,
  [VirtualDomElements.Aside]: ElementTag.Aside,
  [VirtualDomElements.Audio]: ElementTag.Audio,
  [VirtualDomElements.BlockQuote]: ElementTag.BlockQuote,
  [VirtualDomElements.Br]: ElementTag.Br,
  [VirtualDomElements.Button]: ElementTag.Button,
  [VirtualDomElements.Canvas]: ElementTag.Canvas,
  [VirtualDomElements.Circle]: ElementTag.Circle,
  [VirtualDomElements.Cite]: ElementTag.Cite,
  [VirtualDomElements.Code]: ElementTag.Code,
  [VirtualDomElements.Col]: ElementTag.Col,
  [VirtualDomElements.ColGroup]: ElementTag.ColGroup,
  [VirtualDomElements.Data]: ElementTag.Data,
  [VirtualDomElements.Dd]: ElementTag.Dd,
  [VirtualDomElements.Defs]: ElementTag.Defs,
  [VirtualDomElements.Del]: ElementTag.Del,
  [VirtualDomElements.Div]: ElementTag.Div,
  [VirtualDomElements.Dl]: ElementTag.Dl,
  [VirtualDomElements.Dt]: ElementTag.Dt,
  [VirtualDomElements.Ellipse]: ElementTag.Ellipse,
  [VirtualDomElements.Em]: ElementTag.Em,
  [VirtualDomElements.Figcaption]: ElementTag.Figcaption,
  [VirtualDomElements.Figure]: ElementTag.Figure,
  [VirtualDomElements.Footer]: ElementTag.Footer,
  [VirtualDomElements.Form]: ElementTag.Form,
  [VirtualDomElements.G]: ElementTag.G,
  [VirtualDomElements.H1]: ElementTag.H1,
  [VirtualDomElements.H2]: ElementTag.H2,
  [VirtualDomElements.H3]: ElementTag.H3,
  [VirtualDomElements.H4]: ElementTag.H4,
  [VirtualDomElements.H5]: ElementTag.H5,
  [VirtualDomElements.H6]: ElementTag.H6,
  [VirtualDomElements.Head]: ElementTag.Head,
  [VirtualDomElements.Header]: ElementTag.Header,
  [VirtualDomElements.Hr]: ElementTag.Hr,
  [VirtualDomElements.Html]: ElementTag.Html,
  [VirtualDomElements.I]: ElementTag.I,
  [VirtualDomElements.Iframe]: ElementTag.Iframe,
  [VirtualDomElements.Img]: ElementTag.Img,
  [VirtualDomElements.Input]: ElementTag.Input,
  [VirtualDomElements.Ins]: ElementTag.Ins,
  [VirtualDomElements.Kbd]: ElementTag.Kbd,
  [VirtualDomElements.Label]: ElementTag.Label,
  [VirtualDomElements.Li]: ElementTag.Li,
  [VirtualDomElements.Line]: ElementTag.Line,
  [VirtualDomElements.Main]: ElementTag.Main,
  [VirtualDomElements.Meta]: ElementTag.Meta,
  [VirtualDomElements.Nav]: ElementTag.Nav,
  [VirtualDomElements.Ol]: ElementTag.Ol,
  [VirtualDomElements.Option]: ElementTag.Option,
  [VirtualDomElements.P]: ElementTag.P,
  [VirtualDomElements.Path]: ElementTag.Path,
  [VirtualDomElements.Polygon]: ElementTag.Polygon,
  [VirtualDomElements.Polyline]: ElementTag.Polyline,
  [VirtualDomElements.Pre]: ElementTag.Pre,
  [VirtualDomElements.Quote]: ElementTag.Quote,
  [VirtualDomElements.Rect]: ElementTag.Rect,
  [VirtualDomElements.Search]: ElementTag.Search,
  [VirtualDomElements.Section]: ElementTag.Section,
  [VirtualDomElements.Select]: ElementTag.Select,
  [VirtualDomElements.Span]: ElementTag.Span,
  [VirtualDomElements.Strong]: ElementTag.Strong,
  [VirtualDomElements.Style]: ElementTag.Style,
  [VirtualDomElements.Svg]: ElementTag.Svg,
  [VirtualDomElements.Table]: ElementTag.Table,
  [VirtualDomElements.TBody]: ElementTag.TBody,
  [VirtualDomElements.Td]: ElementTag.Td,
  [VirtualDomElements.TextArea]: ElementTag.TextArea,
  [VirtualDomElements.Tfoot]: ElementTag.Tfoot,
  [VirtualDomElements.Th]: ElementTag.Th,
  [VirtualDomElements.THead]: ElementTag.THead,
  [VirtualDomElements.Time]: ElementTag.Time,
  [VirtualDomElements.Title]: ElementTag.Title,
  [VirtualDomElements.Tr]: ElementTag.Tr,
  [VirtualDomElements.Ul]: ElementTag.Ul,
  [VirtualDomElements.Use]: ElementTag.Use,
  [VirtualDomElements.Video]: ElementTag.Video,
}

export const getElementTag = (type: number): string => {
  const elementTag = elementTagMap[type]
  if (elementTag) {
    return elementTag
  }
  throw new Error(`element tag not found ${type}`)
}
